//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fractions.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Fractions.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accuracy of {0} is not allowed! Have to be above 0..
        /// </summary>
        internal static string AccuracyIsLessThanOrEqualToZero {
            get {
                return ResourceManager.GetString("AccuracyIsLessThanOrEqualToZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The string &apos;{0}&apos; cannot be converted to fraction..
        /// </summary>
        internal static string CannotConvertToFraction {
            get {
                return ResourceManager.GetString("CannotConvertToFraction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The comparing instance must be of type {0}. The supplied argument is of type {1}.
        /// </summary>
        internal static string CompareToArgumentException {
            get {
                return ResourceManager.GetString("CompareToArgumentException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} shall be divided by zero..
        /// </summary>
        internal static string DivideByZero {
            get {
                return ResourceManager.GetString("DivideByZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid denominator value: {0}..
        /// </summary>
        internal static string InvalidDenominatorValue {
            get {
                return ResourceManager.GetString("InvalidDenominatorValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid numerator value: {0}..
        /// </summary>
        internal static string InvalidNumeratorValue {
            get {
                return ResourceManager.GetString("InvalidNumeratorValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid token type {0} (expected {1})..
        /// </summary>
        internal static string InvalidTokenType {
            get {
                return ResourceManager.GetString("InvalidTokenType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NaN values are not supported..
        /// </summary>
        internal static string NaNNotSupported {
            get {
                return ResourceManager.GetString("NaNNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Negative infinity (-Infinity) is not supported..
        /// </summary>
        internal static string NegativeInfinityNotSupported {
            get {
                return ResourceManager.GetString("NegativeInfinityNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Positive infinity (+Infinity) is not supported..
        /// </summary>
        internal static string PositiveInfinityNotSupported {
            get {
                return ResourceManager.GetString("PositiveInfinityNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type {0} is not supported..
        /// </summary>
        internal static string TypeXnotSupported {
            get {
                return ResourceManager.GetString("TypeXnotSupported", resourceCulture);
            }
        }
    }
}
